-- Arbiter v2 watcher-first baseline schema

begin;

-- Core market data snapshots
create table if not exists public.market_snapshots (
  id bigserial primary key,
  ts timestamptz not null default now(),
  exchange text not null,
  symbol text not null,
  spot_bid numeric,
  spot_ask numeric,
  perp_bid numeric,
  perp_ask numeric,
  funding_rate numeric,
  mark_price numeric,
  index_price numeric
);

create index if not exists market_snapshots_ts_desc_idx
  on public.market_snapshots (ts desc);

create index if not exists market_snapshots_exchange_symbol_ts_desc_idx
  on public.market_snapshots (exchange, symbol, ts desc);

-- Strategy opportunities generated by detectors
create table if not exists public.opportunities (
  id bigserial primary key,
  ts timestamptz not null default now(),
  exchange text not null,
  symbol text not null,
  type text not null,
  net_edge_bps numeric,
  expected_daily_bps numeric,
  confidence numeric,
  status text not null default 'new',
  details jsonb not null default '{}'::jsonb
);

create index if not exists opportunities_ts_desc_idx
  on public.opportunities (ts desc);

create index if not exists opportunities_exchange_symbol_ts_desc_idx
  on public.opportunities (exchange, symbol, ts desc);

-- Pipeline run status storage
create table if not exists public.system_ticks (
  id bigserial primary key,
  ts timestamptz not null default now(),
  ingest_errors int not null default 0,
  ingest_errors_json jsonb not null default '[]'::jsonb,
  detect_summary jsonb not null default '{}'::jsonb
);

create index if not exists system_ticks_ts_desc_idx
  on public.system_ticks (ts desc);

-- Evaluation/decision audit trail
create table if not exists public.opportunity_decisions (
  id bigserial primary key,
  ts timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  opportunity_id bigint not null references public.opportunities(id) on delete cascade,
  variant text not null,
  score numeric,
  chosen boolean not null default false,
  features jsonb not null default '{}'::jsonb,
  reject_reason text,
  reject_meta jsonb not null default '{}'::jsonb
);

create index if not exists opportunity_decisions_ts_desc_idx
  on public.opportunity_decisions (ts desc);

create index if not exists opportunity_decisions_user_ts_desc_idx
  on public.opportunity_decisions (user_id, ts desc);

create index if not exists opportunity_decisions_opportunity_idx
  on public.opportunity_decisions (opportunity_id);

create index if not exists opportunity_decisions_reject_reason_idx
  on public.opportunity_decisions (reject_reason);

-- RLS: auth users can read watcher outputs; own decision rows only.
alter table public.market_snapshots enable row level security;
alter table public.opportunities enable row level security;
alter table public.system_ticks enable row level security;
alter table public.opportunity_decisions enable row level security;

-- Make policy creation idempotent across reruns.
drop policy if exists "market_snapshots_select_auth" on public.market_snapshots;
drop policy if exists "opportunities_select_auth" on public.opportunities;
drop policy if exists "system_ticks_select_auth" on public.system_ticks;
drop policy if exists "opportunity_decisions_select_own" on public.opportunity_decisions;

create policy "market_snapshots_select_auth"
  on public.market_snapshots
  for select
  to authenticated
  using (true);

create policy "opportunities_select_auth"
  on public.opportunities
  for select
  to authenticated
  using (true);

create policy "system_ticks_select_auth"
  on public.system_ticks
  for select
  to authenticated
  using (true);

create policy "opportunity_decisions_select_own"
  on public.opportunity_decisions
  for select
  to authenticated
  using (user_id = auth.uid());

commit;
